project:
  type: website
  output-dir: _site

website:
  title: "Alexander van Twisk — Statistical Consulting"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: services.qmd
        text: Services
      - href: about.qmd
        text: About

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
